api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Vagaro Appointments"
handle = "vagaro-appointments"
description = "View and checkout Vagaro appointments in POS"

[[extensions.targeting]]
module = "./src/Tile.js"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.js"
target = "pos.home.modal.render"
